{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "bind-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bind-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bind-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval }}
{{- end }}
