{{- if .Values.enabled }}
{{- range .Values.IsovalentEgressGatewayPolicies }}
apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: {{ .namespace }}-egw-policy
spec:
  destinationCIDRs:
    - 0.0.0.0/0
  selectors:
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: {{ .namespace }}
  azAffinity: {{ .azAffinity | default $.Values.azAffinity | default "localOnlyFirst" }}
  egressGroups:
  {{- range .ips }}
  - nodeSelector:
      matchLabels:
        egressgtw: "true"
    egressIP: {{ . }}
    {{- end }}
---
{{- end }}
{{- end }}
