# clusterName: <string> - mandatory, name of the hcp cluster
clusterName: ~
# clusterNamespace: <string> - optional, overrides the default hcp namespace {clusterName-clusterName}
clusterNamespace: ~
# backupNamespace: <string> - mandatory, namespace for helmchart deployment
backupNamespace: ~
# backupSchedule: <string> - crontab notation for etcd backup schedule
backupSchedule: "0 * * * *"
# retentionDays: <int> - how many days to keep old backups during cleanup phase
retentionDays: 30
# etcdStatefulSetName: <string> - optional, overrides the default etcd statefulset neme in hcp namespace
etcdStatefulSetName: etcd

objectBucketClaim:
  # create: <bool> - optional, creates an ObjectBucketClaim for storing etcd backups in {backupNamespace}
  #                  if set to false; backup will use existing ObjectBucketClaim referenced with {objectBucketClaim.name}
  create: false
  # name: <string> - optional, overrides the default ObjectBucketClaim name etcd-hcp-{clusterName}-backup
  #                  mandatory when useing an existing ObjectBucketClaim
  name: ~
  # storageClass: <string> - optional, defines a storageClass for the ObjectBucketClaim
  storageClass: "ocs-storagecluster-ceph-rgw"


# Set this when using a self-signed certificate for s3 storage endpoint
# selfSignedCertificate:
#   configMap: config-map-name-with-ca
#   name: ca-certifiacte-name

image:
  awscli: amazon/aws-cli:2.24.27
  ocpcli: registry.redhat.io/openshift4/ose-cli:v4.15
  etcd: registry.redhat.io/openshift4/ose-etcd:v4.12
