apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: checkpoint-registrator-rb
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: checkpoint-registrator-r
subjects:
  - kind: ServiceAccount
    name: checkpoint-registrator-sa