apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: checkpoint-registrator-r
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - list
      - get
      - update
      - delete