---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quay-obj-backup.fullname" . }}
  namespace: {{ .Values.backupNamespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}