# Default values for bind-exporter
nameOverride: ""                         # optional customization for the chart name portion in the generated resource names. Example: If your chart is named "bind-exporter" and you set nameOverride: "custom", resources would be named like: release-name-custom
fullnameOverride: ""                     # similar to nameOverride but for the full name of the resources. Example: If you set fullnameOverride: "custom", resources would be simply named: custom
namespace: apc-monitoring-bind           # namespace where bind-exporter will be deployed       
replicaCount: 1

image:
  repository: prometheuscommunity/bind-exporter
  tag: v0.8.0
  pullPolicy: IfNotPresent

bindStats:
  url: "http://10.111.126.2:8053"             #<http://bind-server:statistics_port>
resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

deployment:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

podMonitor:
  enabled: true
  interval: 30s

grafanaDashboard:
  enabled: true                     # Grafana dashboard will be deployed only once with the first instance of bind-exporter. For any additional instances set this to false.
  namespace: "apc-observability"    # Namespace where the Grafana dashboard will be deployed
  folder: "apc-observability"       # Folder name in Grafana where the dashboard will be placed
  datasourceName: "prometheus"      # Name of the Prometheus datasource in Grafana
  instanceSelector:
    dashboards: "apc-grafana"       # Set the labels for matching with Grafana instance
  labels:                           # Labels for the Grafana dashboard
    app: grafana
    dashboard: bind-exporter
  
  
networkPolicy:
  enabled: true
  # Ingress rules for metrics endpoint
  metrics:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: openshift-user-workload-monitoring 
    podSelector:
      matchLabels:
        app.kubernetes.io/name: prometheus
  # Additional ingress rules if needed
  additionalRules: []
  # Example of additional rules:
  # - from:
  #   - namespaceSelector:
  #       matchLabels:
  #         name: other-namespace
  #     podSelector:
  #       matchLabels:
  #         app: other-app
