{{- if eq ( .Values.clusterLabelKyverno | toString ) "false" }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-bundle
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.cacert | indent 4 }}
{{- end }}
