apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-flow-infra
  namespace: {{ .Values.namespace }}
spec:
  filters:
  - tag_normaliser: {}
  match:
  - exclude:
      {{- with .Values.auditContainerNames }}
      container_names:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  - select:
    {{- if eq (default .Values.clusterName "") "local" }}
      namespaces: []
    {{- else }}
      {{- with .Values.systemNamespaces }}
      namespaces:
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
      hosts: []
      labels: {}
  globalOutputRefs:
  - loki-out-infra
