{{- if ne (default .Values.clusterName "") "rancher" }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-flow-app
  cluster: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  filters:
  - tag_normaliser: {}
  match:
  - exclude:
      {{- with .Values.systemNamespaces }}
      namespaces:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  - select:
      container_names: []
      hosts: []
      labels: {}
  globalOutputRefs:
  - loki-out-app
{{- end }}
