apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -c -v
    kompose.version: 1.21.0 (992df58d8)
  labels:
    app.kubernetes.io/name: mongodb-express
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/component: database-client
  name: {{ .Values.name }}-mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-express
      app.kubernetes.io/part-of: {{ .Values.name }}
      app.kubernetes.io/component: database-client
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-express
        app.kubernetes.io/part-of: {{ .Values.name }}
        app.kubernetes.io/component: database-client
    spec:
      containers:
      - env:
        - name: ME_CONFIG_BASICAUTH
          value: "true"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-{{ .Values.database | default "admin" }}-{{ .Values.admin_username | default "root" }}
              key: password
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-{{ .Values.database | default "admin" }}-{{ .Values.admin_username | default "root" }}
              key: username
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "false"
        - name: ME_CONFIG_MONGODB_URL
          # value: mongodb://my-user:blabla@{{ .Values.mongo_server | default "mongodb-svc" }}:27017/admin?ssl=false
          valueFrom: 
            secretKeyRef:
              name: mongodb-{{ .Values.database | default "admin" }}-{{ .Values.admin_username | default "root" }}
              key: connectionString.standard
        - name: ME_CONFIG_SITE_BASEURL
          value: /{{ .Values.name }}/mongo-ui/
        image: {{ .Values.image }}
        imagePullPolicy: ""
        name: {{ .Values.name }}-mongodb-express
        ports: 
        - containerPort: 8081
        resources:
          limits:
            memory: "536870912"
          requests:
            memory: "33554432"
      nodeSelector:
{{- range $key, $value := .Values.nodeSelector }}
        "{{ $key }}": "{{ $value }}"
{{- end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
