apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongodb-express
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/component: database-client
  name: {{ .Values.service_name | default .Values.name }}-mongodb-express
spec:
  selector:
    app.kubernetes.io/name: mongodb-express
    app.kubernetes.io/part-of: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
