{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{ if .Values.ingress.path }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- end }}
  labels:
    app.kubernetes.io/name: mongodb-express
    app.kubernetes.io/part-of: "{{ .Values.name }}"
    app.kubernetes.io/component: database-client
  name: "{{ .Values.name }}-mongodb-express"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "/{{ .Values.ingress.path }}"
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.service_name | default .Values.name }}-mongodb-express"
            port:
              number: 8081
{{ end -}}