apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  {{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
  {{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.agentEnvs }}
  agentEnvVars:
{{ toYaml .Values.agentEnvs | indent 4 }}
  {{- end }}
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  {{- if .Values.defaultPodSecurityAdmissionConfigurationTemplateName }}
  defaultPodSecurityAdmissionConfigurationTemplateName: {{ .Values.defaultPodSecurityAdmissionConfigurationTemplateName }}
  {{- end }}  
  {{- if .Values.defaultPodSecurityPolicyTemplateName }} 
  defaultPodSecurityPolicyTemplateName: {{ .Values.defaultPodSecurityPolicyTemplateName }} 
  {{- end }}  
  {{- if .Values.fleetAgentDeploymentCustomization }}
  fleetAgentDeploymentCustomization:  {{ .Values.fleetAgentDeploymentCustomization }}   
  {{- end }}  
  {{- if .Values.kubernetesVersion }}  
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  {{- end }}
  {{- if .Values.rkeConfig.localClusterAuthEndpoint.enabled }}
  localClusterAuthEndpoint:
    enabled: {{ .Values.rkeConfig.localClusterAuthEndpoint.enabled }}
    {{- if .Values.rkeConfig.localClusterAuthEndpoint.fqdn }}
    fqdn: {{ .Values.rkeConfig.localClusterAuthEndpoint.fqdn }}
    {{- end }}
    {{- if .Values.rkeConfig.localClusterAuthEndpoint.caCerts }}
    caCerts: {{ .Values.rkeConfig.localClusterAuthEndpoint.caCerts }}
    {{- end }}
  {{- end }}
  {{- if .Values.enableNetworkPolicy }}
  enableNetworkPolicy: {{ .Values.enableNetworkPolicy }}
  {{- end }}
  # specify rancher helm chart values deployed into downstream cluster
  # rancherValues: {}
  rkeConfig:
    #
    # all possible values are liste here https://docs.rke2.io/reference/server_config
    #
    {{- if ne .Values.cloudprovider "custom" }}
    machinePools:
    {{- if .Values.nodepools }} {{ range $index, $nodepool := .Values.nodepools }}
    - controlPlaneRole: {{ default "false" $nodepool.controlplane }}
      etcdRole: {{ default "false" $nodepool.etcd }}
      workerRole: {{ default "false" $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $nodepool.name }}
      {{- if $nodepool.labels }}
      labels:
{{ toYaml $nodepool.labels | indent 8 }}
      {{- end }}
      {{- if $nodepool.taints }}
      taints:
{{ toYaml $nodepool.taints | indent 8 }}
      {{- end }}
      machineConfigRef:
        {{- if eq $.Values.cloudprovider "amazonec2" }}
        kind: Amazonec2Config
        {{- else if eq $.Values.cloudprovider "vsphere" }}
        kind: VmwarevsphereConfig
        {{- else if eq $.Values.cloudprovider "harvester" }}
        kind: HarvesterConfig
        {{- else if eq $.Values.cloudprovider "digitalocean" }}
        kind: DigitaloceanConfig
        {{- else if eq $.Values.cloudprovider "azure" }}
        kind: AzureConfig
        {{- end}}
        name: {{ $nodepool.name }}
      {{- if $nodepool.displayName }}
      displayName: {{ $nodepool.displayName }}
      {{- end }}
      {{- if $nodepool.rollingUpdate }}
      rollingUpdate:
        maxUnavailable: {{ $nodepool.rollingUpdate.maxUnavailable }}
        maxSurge: {{ $nodepool.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.nodepool }}
    {{ $nodepool := .Values.nodepool }}
    - controlPlaneRole: {{ $nodepool.controlplane }}
      etcdRole: {{ $nodepool.etcd }}
      workerRole: {{ $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $nodepool.name }}
      {{- if $nodepool.labels }}
      labels:
{{ toYaml $nodepool.labels | indent 8 }}
      {{- end }}
      {{- if $nodepool.taints }}
      taints:
{{ toYaml $nodepool.taints | indent 8 }}
      {{- end }}        
      machineConfigRef:
        {{- if eq $.Values.cloudprovider "amazonec2" }}
        kind: Amazonec2Config
        {{- else if eq $.Values.cloudprovider "vsphere" }}
        kind: VmwarevsphereConfig
        {{- else if eq $.Values.cloudprovider "harvester" }}
        kind: HarvesterConfig
        {{- else if eq $.Values.cloudprovider "digitalocean" }}
        kind: DigitaloceanConfig
        {{- else if eq $.Values.cloudprovider "azure" }}
        kind: AzureConfig
        {{- end}}
        name: {{ $nodepool.name }}
      displayName: {{ $nodepool.displayName }}
      {{- if $nodepool.rollingUpdate }}
      rollingUpdate:
        maxUnavailable: {{ $nodepool.rollingUpdate.maxUnavailable }}
        maxSurge: {{ $nodepool.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.rkeConfig.chartValues }}
    chartValues: 
{{ toYaml .Values.rkeConfig.chartValues | indent 6 }}
    {{- end }}
    etcd:
      {{- if .Values.rkeConfig.etcd.disableSnapshots }}
      disableSnapshots: {{ .Values.rkeConfig.etcd.disableSnapshots }}
      {{- end }}
      {{- if .Values.rkeConfig.etcd.etcdSnapshotDir }}
      etcd-snapshot-dir: {{ .Values.rkeConfig.etcd.etcdSnapshotDir }}
      {{- end }}
      {{- if .Values.rkeConfig.etcd.etcdSnapshotName }}
      etcd-snapshot-name: {{ .Values.rkeConfig.etcd.etcdSnapshotName }}
      {{- end }}
      snapshotRetention: {{ .Values.rkeConfig.etcd.snapshotRetention }}
      snapshotScheduleCron: {{ .Values.rkeConfig.etcd.snapshotScheduleCron }}
      S3:
        {{- if .Values.rkeConfig.etcd.S3.enabled }}
        bucket: {{ .Values.rkeConfig.etcd.S3.bucket }}
        cloudCredentialName: {{ .Values.rkeConfig.etcd.S3.cloudCredentialName }}
        endpoint: {{ .Values.rkeConfig.etcd.S3.endpoint }}
        endpointCA: {{ .Values.rkeConfig.etcd.S3.endpointCA }}
        folder: {{ .Values.rkeConfig.etcd.S3.folder }}
        region: {{ .Values.rkeConfig.etcd.S3.region }}
        skipSSLVerify: {{ .Values.rkeConfig.etcd.S3.skipSSLVerify }}
        {{- end }}
    machineGlobalConfig:
      cluster-cidr: {{ .Values.rkeConfig.machineGlobalConfig.clusterCidr }}
      cluster-dns: {{ .Values.rkeConfig.machineGlobalConfig.clusterDns }}
      cluster-domain: {{ .Values.rkeConfig.machineGlobalConfig.clusterDomain }}
      cni: {{ .Values.rkeConfig.machineGlobalConfig.cni }}
      disable: {{ .Values.rkeConfig.machineGlobalConfig.disable }}
      disable-kube-proxy: {{ .Values.rkeConfig.machineGlobalConfig.disableKubeProxy }}
      {{- if .Values.rkeConfig.machineGlobalConfig.etcdExposeMetrics }}
      etcd-expose-metrics: {{ .Values.rkeConfig.machineGlobalConfig.etcdExposeMetrics }} 
      {{- end }}
      {{- if .Values.rkeConfig.machineGlobalConfig.etcdExposeMetrics }}
      service-node-port-range: {{ .Values.rkeConfig.machineGlobalConfig.serviceNodePortRange }}
      {{- end }}
      {{- if .Values.rkeConfig.machineGlobalConfig.serviceCidr }}
      service-cidr: {{ .Values.rkeConfig.machineGlobalConfig.serviceCidr }}
      {{- end }}
  
      {{- if .Values.rkeConfig.machineGlobalConfig.kubeApiserverArg }}
      kube-apiserver-arg: {{ .Values.rkeConfig.machineGlobalConfig.kubeApiserverArg }}
      {{- end }}
      {{- if .Values.rkeConfig.machineGlobalConfig.kubeSchedulerArg }}
      kube-scheduler-arg: {{ .Values.rkeConfig.machineGlobalConfig.kubeSchedulerArg }}
      {{- end }}
      {{- if .Values.rkeConfig.machineGlobalConfig.kubeControllerManagerArg }}
      kube-controller-manager-arg: {{ .Values.rkeConfig.machineGlobalConfig.kubeControllerManagerArg }} 
      {{- end }}
      {{- if .Values.rkeConfig.machineGlobalConfig.secretsEncryption }}
      secrets-encryption: {{.Values.rkeConfig.machineGlobalConfig.secretsEncryption }}
      {{- end }}
      tls-san: {{ .Values.rkeConfig.machineGlobalConfig.tlsSan }}
      {{- if .Values.rkeConfig.machineGlobalConfig.auditPolicyFile }}
      audit-policy-file: >
{{ .Values.rkeConfig.machineGlobalConfig.auditPolicyFile | indent 8}}
      {{- end }}
      profile: {{ .Values.rkeConfig.machineGlobalConfig.profile }}
    
    {{- if .Values.rkeConfig.machineSelectorConfig }}
    machineSelectorConfig:
    {{- range .Values.rkeConfig.machineSelectorConfig }}
      - config:
          profile: {{ .config.profile }}
    {{- end }}
    {{- end }}
        # Node name
        # node-name: ""
        # Disable embedded containerd and use alternative CRI implementation
        # container-runtime-endpoint: ""
        # Override default containerd snapshotter (default: "overlayfs")
        # snapshotter: ""
        # IP address to advertise for node
        # node-ip: "1.1.1.1"
        # Kubelet resolv.conf file
        # resolv-conf: ""
        # Customized flag for kubelet process
        # kubelet-arg: ""
        # Customized flag for kube-proxy process
        # kube-proxy-arg: ""
        # Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults. (default: false)
        # protect-kernel-defaults: false
        # Enable SELinux in containerd (default: false)
        # selinux: true
        # Cloud provider name
        # cloud-provider-name: ""
        # Cloud provider configuration file path
        # cloud-provider-config: ""
    #rodo    
    upgradeStrategy:
      controlPlaneDrainOptions:
        enabled: false
        # deleteEmptyDirData: false
        # disableEviction: false
        # gracePeriod: 0
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 0
      workerDrainOptions:
        enabled: false
        # deleteEmptyDirData: false
        # disableEviction: false
        # gracePeriod: 0
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 0
      workerConcurrency: "10%"
      controlPlaneConcurrency: "10%"
    {{- if .Values.rkeConfig.additionalManifest }}
    additionalManifest: |
{{ .Values.rkeConfig.additionalManifest | indent 6 }}
    {{- end }}
