apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.defaultNamespace }}
  name: cronjob-etcd-backup-{{ .Values.clusterName }}
  labels:
    app.kubernetes.io/name: cronjob-etcd-backup-{{ .Values.clusterName }}
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged