apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: etcd-backup-failure-alert-{{ .Values.clusterName }}
  namespace: {{ .Values.defaultNamespace }}
spec:
  groups:
  - name: cronjob.rules
    rules:
    - alert: EtcdCronJobFailure
      expr: kube_job_status_failed{namespace="apc-backup", job_name=~"cronjob-etcd-backup-.*"} > 0
      labels:
        severity: critical
      annotations:
        summary: "ETCD Backup CronJob has failed"
        description: "CronJob cronjob-etcd-backup-{{ .Values.clusterName }} in namespace apc-backup has failed."