kind: ServiceAccount
apiVersion: v1
metadata:
  name: cronjob-etcd-backup-{{ .Values.clusterName }}
  namespace: {{ .Values.defaultNamespace }}
  labels:
    app.kubernetes.io/name: cronjob-etcd-backup-{{ .Values.clusterName }}