{{- if and (hasKey .Values "objectBucketClaim") (hasKey .Values.objectBucketClaim "create") (.Values.objectBucketClaim.create) -}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "obc.name" . }}
  namespace: {{ default .Values.backupNamespace .Values.objectBucketClaim.namespaceOverride }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  generateBucketName: {{ include "obc.name" . }}
  storageClassName: {{ default "openshift-storage.noobaa.io" .Values.objectBucketClaim.storageClass }}
{{- end -}}
