apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vsphere-config-secret
  namespace: kube-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-lab-cluster-ss
  data:
    - remoteRef:
        key: private-cloud/data/lab/vsphere/eso-dev-csi
        property: password
      secretKey: password
    - remoteRef:
        key: private-cloud/data/lab/vsphere/eso-dev-csi
        property: username
      secretKey: username
  target:
    name: vsphere-config-secret
    template:
      engineVersion: v2
      data:
        csi-vsphere.conf: |
          [Global]
          cluster-id = "{{ .Values.clusterName }}-cluster"
          user = "{{`{{`}} .username {{`}}`}}"
          password = "{{`{{`}} .password {{`}}`}}"
          port = "443"
          insecure-flag = "{{ .Values.insecureFlag }}"
          [VirtualCenter "{{ .Values.virtualCenter }}"]
          datacenters = "{{ .Values.dataCenters }}"
