apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cluster-flow-exclude-namespaces-audit-filter
  namespace: {{ .Values.clusterWideResourceNamespace }}
spec:
  filters:
    - tag_normaliser: {}
    - dedot:
        de_dot_nested: true
        de_dot_separator: '-'
    - grep:
        regexp:
        - key: {{ .Values.key }}
          pattern: {{ .Values.pattern }}
  globalOutputRefs:
    - cluster-output-elastic-audit
    - cluster-output-siem-syslog
  match:
    - exclude:
        namespaces: {{ toYaml .Values.excludedNamespaces | nindent 10 }}
    - select:
        container_names: []
        hosts: []
        labels: {}