apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-output-elastic-audit
  namespace: {{ .Values.clusterWideResourceNamespace }}
spec:
  elasticsearch:
    host: {{ .Values.elastic_host }}
    password:
      valueFrom:
        secretKeyRef:
          key: elastic
          name: es1-es-elastic-user
    port: {{ .Values.elastic_port}}
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: false
    user: {{ .Values.elastic_user}}
    index_name: {{ .Values.index_name_audit_logs}}
    include_timestamp: true
    buffer:
      timekey: {{ .Values.timekey }}
      timekey_use_utc: true
      timekey_wait: {{ .Values.timekey_wait }}