apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-output-siem-syslog
  namespace: {{ .Values.clusterWideResourceNamespace }}
spec:
  syslog:
    buffer:
      timekey: {{ .Values.timekey }}
      timekey_use_utc: true
      timekey_wait: {{ .Values.timekey_wait }}
    format:
      app_name_field: kubernetes.labels.app
      hostname_field: kubernetes.host
      log_field: message
    host: {{ .Values.syslog_host }}
    insecure: true
    port: {{ .Values.syslog_port }}
    transport: {{ .Values.syslog_transport }}