enabled: true

# list of objects containing namespace and ip to source nat all outgoing egress traffic to
#  - namespace: kafka
#    ip: 10.90.31.50
#  - namespace: admin-console
#    ip: 10.90.31.51
CiliumEgressGatewayPolicies: []
